version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: springboot-mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-network

volumes:
  mysql-data:

networks:
  springboot-network:
